version: "3.9"
services:
  javazone:
    image: viqueen/javazone-2022:workshop
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - ~/workshop-sources/viqueen/jdk:/workshop-sources/jdk
      - ~/workshop-sources/viqueen/javazone-2022:/workshop-sources/javazone-2022
